name = "io_utils"
description = "A terminal IO library"
version = "1.0.0"
licenses = "GPL-3.0-only"

authors = ["Dylan E."]
maintainers = ["Dylan E. <76961140+KvanQuilst@users.noreply.github.com>"]
maintainers-logins = ["kvanquilst"]

project-files = ["io_utils.gpr"]

[available.'case(os)']
linux   = true
macos   = false
windows = false
'...'   = false

[origin]
commit = "0d8f237ffd3cac485e629a3bf007bd1ad01edfc4"
url = "git+https://github.com/KvanQuilst/IO_Utils.git"
